version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      # Host interno del servicio MySQL en Dokploy (solo el hostname, no URL completa)
      - DB_HOST=infradb-mysqlmain-j1dmbb
      - DB_PORT=3306
      - DB_USERNAME=admin
      - DB_PASSWORD=KkpjCL8XpWQXDufIIifR
      - DB_DATABASE=nuntius
      - JWT_SECRET=WF//xrxgqyEpIZk7PKOS0LEYMTcwS7oGK7/JCJxvGvw=
      - JWT_EXPIRES_IN=120m
      - NODE_ENV=production
    networks:
      - dokploy-network # Para que pueda hablar con la red del panel
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # 2. IMPORTANTE: En Dokploy NO mapeamos puertos 80:80 manualmente.
    # Traefik (el proxy de Dokploy) se encarga de eso mediante la red.
    expose:
      - "80" 
    depends_on:
      - backend
    networks:
      - dokploy-network
    restart: unless-stopped

# 3. Definimos la red externa que usa Dokploy para que Traefik vea tus contenedores
networks:
  dokploy-network:
    external: true
